version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    ports:
    - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    depends_on:
      - elasticsearch
    #in kibana set elastic search host in enviorment variable
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200/
    ports:
      - "5601:5601"

  logstash:
    container_name: logstash
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    #in logstash set elastic search host in enviorment variable
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200/
    ports:
      - "5000:5000"
    #command - use to run a command in docker container. This is logstash command
    command: logstash -f pipeline/logstash.conf --path.data LOGSTASH_HOME/data

